name: Test Action

on:
  push:
    branches:
      - main  # Change this to any branch you want to trigger the action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 22f2001395@ds.study.iitm.ac.in
        run: echo "Hello, world!"
